# Generated by Django 6.0.6 on 2026-06-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('prazo_entrega_dias', models.IntegerField(default=3)),
                ('avaliacao', models.FloatField(default=5.0)),
                ('ativo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, to='scm.categoria')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='PedidoEDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=30, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio_edi', models.DateTimeField(blank=True, null=True)),
                ('data_previsao_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado ao Fornecedor'), ('CONFIRMADO', 'Confirmado pelo Fornecedor'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='GERADO', max_length=20)),
                ('valor_total', models.FloatField(default=0.0)),
                ('mensagem_edi', models.TextField(blank=True)),
                ('ia_justificativa', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Pedidos EDI',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('preco_unitario', models.FloatField(default=0.0)),
                ('estoque_atual', models.FloatField(default=0.0)),
                ('estoque_minimo', models.FloatField(default=20.0)),
                ('perecivel', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sugerida_ia', models.FloatField(default=0)),
                ('quantidade_pedida', models.FloatField(default=0)),
                ('preco_unitario', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='scm.pedidoedi')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.produto')),
            ],
            options={
                'verbose_name_plural': 'Itens de Pedido',
            },
        ),
        migrations.CreateModel(
            name='RecomendacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_recomendada', models.FloatField()),
                ('justificativa', models.TextField()),
                ('contexto', models.TextField(blank=True)),
                ('confianca', models.FloatField(default=0.8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.produto')),
            ],
            options={
                'verbose_name_plural': 'Recomendações IA',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='VendaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('quantidade_vendida', models.FloatField()),
                ('preco_unitario', models.FloatField()),
                ('promocao_ativa', models.BooleanField(default=False)),
                ('estoque_atual', models.FloatField(default=0.0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.produto')),
            ],
            options={
                'verbose_name_plural': 'Vendas Históricas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
